sudo: required

dist: trusty

osx_image: xcode7.3

os:
  - linux
  - osx

language: node_js

node_js:
  - 7
  - node

branches:
  only: master

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install g++-4.9;
      export CXX='g++-4.9';
    fi

install:
  - make config
  - npm install

script: make test-cov

after_success: make send-cov

notifications:
  email:
    on_success: never
