sudo: required

dist: trusty

osx_image: xcode7.3

os:
  - linux
  - osx

language: node_js

node_js:
  - 7
  - node

branches:
  only: master

before_install:
  - test $TRAVIS_OS_NAME == "osx" && brew install --with-default-names gnu-sed || :;
  - sed -i "s/^    \"hacktimer.*$//" package.json;
  - sed -i "/\"hacktimer/,+4d" package-lock.json;
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install gcc-4.9;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50;
      sudo apt-get install g++-4.9;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50;
    fi

install:
  - make config
  - npm install

script: make test-cov

after_success: make send-cov

notifications:
  email:
    on_success: never
