matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

language: node_js

node_js:
  - 7
  - node

branches:
  only: master

install: npm install

script: npm run test-cov

after_success: npm run send-cov

notifications:
  email:
    on_success: never
